name: Bundle Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-bundle-size
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: "build"
          compression: "none"
          pattern: "./dist/**/*.{mjs,js}"
